### ISSUE TITLE
successive use of search-and-replace 

### ISSUE THREAD

**Issue by ivan31100** [phip1611/docx4j-search-and-replace-util#10]
If a string text is splitted by more than 3 org.docx4j.wml.Text, at the end of processus, we get 3 org.docx4j.wml.Text : 
* First Text contains value = complete Text
* Second Text contains value = null
* Third Text contains value = ""

The problem is when I do again searchAndReplace, the lib failed in method buildMetaItemList, line 136 (since value = null ):
```java
for (Text text : texts) {
	int length = text.getValue().length(); // <-------
	list.add(new TextMetaItem(index, index + length - 1, text, iteration));
	index += length;
	iteration++;
}
```

I solved the problem by set "" instead null line 234 in method executeReplaceCommand : 

```java
// null all Text-objects that may be in between

if (tmi2.getPosition() - tmi1.getPosition() > 1) {
	int upperBorder = tmi2.getPosition();
	int lowerBorder = tmi1.getPosition() + 1;
	for (int i = lowerBorder; i < upperBorder; i++) {
		texts.get(i).setValue("");
	}
}
```

I'm not sure that is the good correction ...

**Comment by phip1611** [comment]
Hey, thanks for using my lib and submitting this issue. Probably, setting the value to the empty string is the better option. I'll look into it next week!
