### ISSUE TITLE
Evaluate docx4j 8.x vs 11.x

### ISSUE THREAD

**Issue by phip1611** [phip1611/docx4j-search-and-replace-util#6]
Would there be any benefit when I use 11.x? 8.x definitely works on Java 8 AND Java 11 and it still gets updates.

**Comment by seazzle** [comment]
Hi :) first thanks for your library. I really appreciate that you share your thoughts and built this library.
While testing it, I found a small issue with current docx4J version / java version

In de.phip1611.Docx4JSRUtil#getAllElementsOfType you have the condition:
`if (obj instanceof JAXBElement)` while `import javax.xml.bind.JAXBElement;`.

However in the latest version JAXBElement package structure changed and should imho be adopted to jakarta.xml.bind.JAXBElement.

Let me know :)

**Comment by nexus061** [comment]
Hi, i have open this pull request https://github.com/phip1611/docx4j-search-and-replace-util/pull/16

java 11, docx4j 11 and latest jackarta xml

**Comment by nexus061** [comment]
@phip1611 can the pull request be fine?

**Comment by phip1611** [comment]
Hi @nexus061 - very cool, thank you! I'll have a closer look soon.
