### ISSUE TITLE
Line Breaks in Replacement Text

### ISSUE THREAD

**Issue by Zahraa847** [phip1611/docx4j-search-and-replace-util#9]
Hi,
How can I insert line breaks in the replacement text?
So far, wherever I perform a sub-replacement to insert "</w:t><w:br/><w:t>" for those break-placeholders, it just gets printed as characters into the document.

**Comment by phip1611** [comment]
Hi @Zahraa847
Thanks for your interest in this project :)
Unfortunately, this is currently not possible. I think, this needs a bigger refactoring of the code. However, I'm not quite sure how MS Word handles line breaks..

If you want, you can work in this, submit an PR, and I'll be happy to work with you together to get that thing merged.

**Comment by Zahraa847** [comment]
Thanks for your concern!
I was able to solve it by adding Br object to run when replacing placeholder within paragraph in Docx4j..
Actually this Util perfectly works on simple labels and single lines

**Comment by phip1611** [comment]
@Zahraa847 If you could provide some more information how you solved it exactly, this would help others people as well, I think. :) I received this question multiple times for this library and it seems like you are the first person to solve it
